import 'package:auto_route/auto_route.dart';

import 'package:{{pkg}}/core/custom_transition_builders.dart';
// Generated by auto_route as a standalone library, hence import (not part).
import '{{name}}_router_module.gr.dart';

// dart run build_runner build --delete-conflicting-outputs
@AutoRouterConfig(
  generateForDir: ['lib/features/{{name}}/presentation/screens'],
  replaceInRouteName: 'Screen,Route',
)
class {{Pascal}}RouterModule extends RootStackRouter {
  @override
  RouteType get defaultRouteType => RouteType.custom(
        transitionsBuilder: customTransitionBuilder,
      );

  @override
  List<AutoRoute> get routes => [
        AutoRoute(page: {{Pascal}}Route.page),
        // TODO: add more routes for this feature
      ];
}

